version: '3.8'
services:
  llm:
    build: .
    container_name: llm
    ports:
      - "3002:3002"
    depends_on:
      - redis_llm
      - qdrant
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "npm install && npm run build && node dist/index.js"
    networks:
      - default
      - demo_demo_backend
  redis_llm:
    image: redis:7.2-alpine
    container_name: redis_llm
    ports:
      - "6380:6379"
    volumes:
      - llm_data:/data
  qdrant:
    image: qdrant/qdrant:v1.14.1
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
volumes:
  qdrant_data: 
  llm_data:

# access the main network
networks:
  demo_demo_backend:
    external: true