version: '3.8'
services:
  llm:
    build: .
    container_name: llm
    ports:
      - "3000:3000"
    depends_on:
      - redis_llm
    volumes:
      - .:/app
    working_dir: /app
    command: npm run dev
  
  redis_llm:
    image: redis:7.2-alpine
    container_name: redis_llm
    ports:
      - "6379:6379"
    volumes:
      - llm_data:/data

volumes:
  llm_data:
